---
- name: Install apache components
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - httpd
    - php
    - php-mysql
    - MySQL-python
        
- name: Allow incoming HTTP connections
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf 
    regexp=^Listen 
    line="Listen 0.0.0.0:80"
  notify: restart apache

- name: Create index
  template: 
    src=index.php.j2 
    dest=/var/www/html/index.php 
    mode=0644
  notify: restart apache

- name: Start Apache
  service: 
    name=httpd 
    state=started 
    enabled=yes
